name: Fetch Subscriptions

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Requests
        run: pip install requests

      - name: Run fetch script
        run: python fetch_subs.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add combined.txt
          git commit -m "Update combined.txt" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
