name: Fetch V2Ray Configurations

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  push:
    branches:
      - main  # Runs when there is a push to the main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch_configs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install requests

    - name: Fetch V2Ray configurations
      run: |
        python fetch_subs.py  # Make sure the script is in the root of the repo

    - name: Pull latest changes from the remote repository
      run: |
        git pull origin main  # Pull the latest changes from the remote main branch

    - name: Add, commit, and push changes
      run: |
        git add .  # Add all changes
        git config user.name "github-actions"  # Set GitHub Actions name
        git config user.email "github-actions@github.com"  # Set email
        git commit -m "Update configuration files" || echo "No changes to commit"
        git push origin main  # Push changes to the remote main branch
